parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:react/recommended

plugins:
  - react

env:
  browser: true
  node: true
  es6: true

rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  quotes:
    - error
    - single
  arrow-parens:
    - error
    - as-needed
  space-before-function-paren:
    - error
    - never
  react/jsx-curly-spacing:
    - 2
    - always
  template-curly-spacing:
    - 2
    - always
  curly: error
  no-var: error
  no-console: off
  prefer-template: error
  no-unused-vars: error
  react/prop-types: off
  arrow-spacing: error
