extends: stylelint-config-standard
plugins:
  - stylelint-order
rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
      - global
  order/order:
    - custom-properties
    - declarations
  order/properties-alphabetical-order:
    - true
